import XCTest
@testable import VRizationCore

final class PoseMathTests: XCTestCase {
    private let identity: [Double] = [1, 0, 0, 0, 1, 0, 0, 0, 1]
    private func assertPose(_ value: Pose, _ yaw: Double, _ pitch: Double, _ roll: Double,
                            file: StaticString = #file, line: UInt = #line) {
        XCTAssertEqual(value.yaw, yaw, accuracy: 1e-9, file: file, line: line)
        XCTAssertEqual(value.pitch, pitch, accuracy: 1e-9, file: file, line: line)
        XCTAssertEqual(value.roll, roll, accuracy: 1e-9, file: file, line: line)
    }
    func testWrappingCrossesEdgeByShortestAngle() throws {
        let radians = Double.pi / 180
        XCTAssertEqual(try PoseMath.relative(-179 * radians, origin: 179 * radians), 2 * radians, accuracy: 1e-9)
        XCTAssertEqual(try PoseMath.relative(179 * radians, origin: -179 * radians), -2 * radians, accuracy: 1e-9)
        XCTAssertEqual(try PoseMath.wrap(750 * radians), 30 * radians, accuracy: 1e-9)
        XCTAssertThrowsError(try PoseMath.wrap(.nan))
    }
    func testIndependentAxesHaveViewerSigns() throws {
        var center = RotationCenter()
        assertPose(try center.sample(screenToWorld: identity), 0, 0, 0)
        // Independent expected axis matrices, not generated by the method under test.
        let y = 0.25, p = 0.3, r = 0.35
        assertPose(try center.sample(screenToWorld: [cos(y), 0, -sin(y), 0, 1, 0, sin(y), 0, cos(y)]), y, 0, 0)
        assertPose(try center.sample(screenToWorld: [1, 0, 0, 0, cos(p), -sin(p), 0, sin(p), cos(p)]), 0, p, 0)
        assertPose(try center.sample(screenToWorld: [cos(r), sin(r), 0, -sin(r), cos(r), 0, 0, 0, 1]), 0, 0, r)
    }
    func testArbitraryTiltedCenterPreservesLocalAxesAndRecenter() throws {
        var center = RotationCenter()
        let origin = try PoseMath.rotation(yaw: 1.1, pitch: 0.7, roll: -0.8)
        assertPose(try center.sample(screenToWorld: origin), 0, 0, 0)
        for expected in [Pose(yaw: 0.3), Pose(pitch: -0.25), Pose(roll: 0.4), Pose(yaw: 0.3, pitch: -0.25, roll: 0.4)] {
            let local = try PoseMath.rotation(yaw: expected.yaw, pitch: expected.pitch, roll: expected.roll)
            assertPose(try center.sample(screenToWorld: PoseMath.multiply(origin, local)), expected.yaw, expected.pitch, expected.roll)
        }
        center.recenter()
        let next = try PoseMath.rotation(yaw: -1.4, pitch: -0.5, roll: 0.6)
        assertPose(try center.sample(screenToWorld: next), 0, 0, 0)
        assertPose(try center.sample(screenToWorld: PoseMath.multiply(next, PoseMath.rotation(yaw: -0.2, pitch: 0.15, roll: -0.3))), -0.2, 0.15, -0.3)
    }
    func testLandscapeRemapTransposesReferenceToDeviceThenChangesBasis() throws {
        let leftBasis: [Double] = [0, -1, 0, 1, 0, 0, 0, 0, 1]
        let rightBasis: [Double] = [0, 1, 0, -1, 0, 0, 0, 0, 1]
        XCTAssertEqual(try PoseMath.screenToWorld(referenceToDevice: identity, landscapeLeft: true), leftBasis)
        XCTAssertEqual(try PoseMath.screenToWorld(referenceToDevice: identity, landscapeLeft: false), rightBasis)
        // A physical local rotation expressed in portrait device coordinates must
        // recover the same screen pose in either landscape orientation.
        let local = try PoseMath.rotation(yaw: 0.2, pitch: -0.15, roll: 0.3)
        for (left, basis) in [(true, leftBasis), (false, rightBasis)] {
            var center = RotationCenter()
            _ = try center.sample(screenToWorld: PoseMath.screenToWorld(referenceToDevice: identity, landscapeLeft: left))
            let deviceToWorld = try PoseMath.multiply(PoseMath.multiply(basis, local), PoseMath.transpose(basis))
            let referenceToDevice = try PoseMath.transpose(deviceToWorld)
            let screen = try PoseMath.screenToWorld(referenceToDevice: referenceToDevice, landscapeLeft: left)
            assertPose(try center.sample(screenToWorld: screen), 0.2, -0.15, 0.3)
        }
    }
    func testInvalidMatrixDoesNotPoisonNextCenter() throws {
        var center = RotationCenter()
        XCTAssertThrowsError(try center.sample(screenToWorld: [1, 2]))
        XCTAssertThrowsError(try center.sample(screenToWorld: [Double.nan, 0, 0, 0, 1, 0, 0, 0, 1]))
        XCTAssertThrowsError(try center.sample(screenToWorld: [2, 0, 0, 0, 1, 0, 0, 0, 1]))
        XCTAssertThrowsError(try center.sample(screenToWorld: [-1, 0, 0, 0, 1, 0, 0, 0, 1]))
        assertPose(try center.sample(screenToWorld: identity), 0, 0, 0)
    }
}
